name: CICD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  CI:
    runs-on: ubuntu-latest
    env:
      DB_NAME: ${{ secrets.DB_NAME }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
    strategy:
      matrix:
        node-version: [10.19.0]
    steps:
      - uses: actions/checkout@v2

      - name: NodeJS Installation ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  CD:
    runs-on: ubuntu-latest
    needs: CI

    steps:
      - uses: actions/checkout@v2

      - name: build image
        run: docker build -t seungbin9850/nestjs .

      - name: publish docker
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: seungbin9850/nestjs
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
